version: "3.8"

services:
  backend:
    image: kiritahir/hello-devops-backend:latest
    container_name: backend-container
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: kiritahir/hello-devops-frontend:latest
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
