version: "3.8"

services:
  backend:
    image: kiritahir/hello-devops-backend:latest-mac
    container_name: backend-container
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app-network

  frontend:
    image: kiritahir/hello-devops-frontend:latest-mac
    container_name: frontend-container
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

